package com.webtest.springboot.service;

import org.springframework.stereotype.Service;
import com.webtest.springboot.model.User;

@Service("userService")
public class UserRepositoryImpl implements UserRepository {

    public boolean isUserEmpty(User user) {
        return (user == null);
    }
    
    @Override
    public User createUser(User user) {
        user.setId("Id generated by the back-end");
        return user;
    }

    @Override
    public boolean isUserExist(User user) {
        return true;
    }
}
